doc/python-spglib.rst

This documents 'hall_number' key that is returned from get_symmetry_dataset

Update python-spglib.rst to account for hall_number

---

src/overlap.c
src/overlap.h

I compiled with `-Wpedantic` this time to make sure there were no GCC extensions accidentally being used.
cc @jochym, can you test this?  I don't have access to a computer with MSVC...

Fix void * arith on MSVC

---

src/overlap.c

[src/overlap.c:558]: (error) Memory leak: found

cppcheck: fix memory leak

---

python/setup.py

There are two branches of the control flow and I assume that both of them should be as similar as possible.

Adding missing metadata to use_setuptools==False branch of setup.py.

---

.travis.yml
python/setup.py
python/test/test_hall_number_from_symmetry.py
python/test/test_niggli_delaunay.py
python/test/test_reciprocal_mesh.py
python/test/test_spglib.py

Testing in Python is usually done via ``python setup.py test``. To enable this for spglib, the test suite has to be defined in setup.py and filesystem paths in tests have to be made relative to setup.py location. This PR contains both fixes. On my machine (Ubuntu 16) all tests for both Python2 and Python3 pass now via ``python{,3} setup.py test``.

Fix python tests

---

src/overlap.c

Partially duplicate a version of `cel_is_overlap_with_same_type` into `overlap.c` to be used in `ovl_check_total_overlap`. Compiler macros are checked to determine if the actual inline keyword (or similar) can be reasonably assumed to work and are pretty conservative as far as I can tell. Otherwise, it falls back to no inlining and hoping that the compiler decides to do it on its own. 
Ideally, checks for support of C99 and other features would be done through something like autoconf, but the fact that there are essentially three separate build systems (autoconf, cmake, and python) makes it harder. That said, it is doable if needed.
On my machine I see a significant increase of performance for `spg_get_dataset` for large highly symmetric structures (80-100%), with a small gain running the …

Small additional overlap.c optimization

---

src/refinement.c
src/spglib.c

Our CI for CP2K discovered a number of memory leaks in the latest spglib version which are fixed with the patch in this PR.
The report from the LeakSanitizer before the fix:
```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/workspace/cp2k/regtesting/local/sdbg/TEST-local-sdbg-2019-02-01_12-54-35/DFTB/regtest-nonscc/si_kp2.inp.out
#10 0x40948b in cp2k /workspace/cp2k/src/start/cp2k.F:281
#11 0x409595 in main /workspace/cp2k/src/start/cp2k.F:45
#12 0x7f9c5da4cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
Direct leak of 56 byte(s) in 1 object(s) allocated from:
#0 0x7f9c5f23bd68 in __interceptor_malloc /opt/cp2k-toolchain/build/gcc-8.2.0/libsanitizer/lsan/lsan_interceptors.cc:52
#1 0x7f9c6028959c in ref_get_exact_structure_and_symmetry …
```

fix memory leak of site_symmetry_symbol members

---

CMakeLists.txt

make the 'check' target output verbose/work on msvc

'check' target on msvc  

---

fortran/spglib_f08.f90

Hi, 
I was trying to use the standardize_cell function from a fortran code and realized the interface was not properly implemented. 
I added spg_standardize_cell and spgat_standardize_cell to the public interface and fixed the return type in the c bindings.

Added standardize_cell to f08 interface

---

src/cell.c
src/delaunay.c

[https://github.com/spglib/spglib/blob/develop/src/primitive.c#L418](url) the argument `min_lattice` and `lattice` point to the same memory-address. This makes [https://github.com/spglib/spglib/blob/develop/src/delaunay.c#L135](url) always equal to identity matrix rather than change-of-basis matrix.
remove redundent assignment in cell.c.

fix(delaunay): fix error in calculating Delaunay change-of-basis matrix

---

.github/workflows/main.yml

Added GitHub Workflows for x86_64, i686, and aarch64 wheel build support.
Related to https://github.com/spglib/spglib/pull/129, @atztogo Could you please review this PR?

Add GitHub Workflows for wheel build support

---

doc/api.rst
doc/python-spglib.rst

The name of `get_hall_number_from_symmetry` may mislead its behavior for symmetry operations with nonstandard settings. This PR adds clarification for the function a bit. 
Related: https://github.com/spglib/spglib/issues/132

Add clarification for `get_hall_number_from_symmetry`

---

CMakeLists.txt
fortran/CMakeLists.txt

* Remove `-Wall` from `CMAKE_C_FLAGS_RELEASE` since it is not portable
* Use `add_definitions` for debugging macros
* Make OpenMP mandatory if `USE_OMP`
* ~~Use `cmakedefine` for `SPGLIB_(MAJOR|MINOR|MICRO)_VERSION`~~

CMake improvements

---

doc/api.rst
doc/dataset.rst
doc/python-spglib.rst

Dr. Seto's page for Hall symbols seems to be moved.

Fix dead links

---

.pre-commit-config.yaml
doc/README.md
doc/index.rst
doc/magnetic_spacegroup.rst
python/_spglib.c
python/spglib/spglib.py
python/test/test_site_tensors.py
src/spacegroup.c
src/spacegroup.h
src/spglib.c
src/spglib.h
src/spin.c
src/spin.h
src/test.c

This is the second PR for supporting magnetic space groups (MSG) in spglib.
- In the python interface, `get_symmetry` with magmoms ≠ None, now returns the `time_reversals` array. True for time-reversal operations, and False for ordinary operations.
- The functions in `spin.c` are fixed and refactored. Now Type-II MSG, which has same-spatial-part operations like g1 and g1’, can be handled.
- Adding an implementation note for MSG detection (`doc/magnetic_spacegroup.rst`). But, I am not sure where to put it.
- Currently, `symprec` is used to compare magmoms. It will be more flexible to add a tolerance parameter for them like magmom_tolerance.
Related: https://github.com/spglib/spglib/issues/150

Return time reversal operations for scalar and vectors

---

doc/api.md
src/spglib.c
src/spglib.h
src/test.c

Change argument position of `num_operations` to the right behind
time_reversals, because it is more intuitive.

Reorder arguments of `spg_get_magnetic_spacegroup_type_from_symmetry`

---

.pre-commit-config.yaml
doc/api.md
doc/python-spglib.md
python/_spglib.c
python/spglib/__init__.py
python/spglib/spglib.py
python/test/conftest.py
python/test/test_hall_number_from_symmetry.py
python/test/test_spacegrouop_type_from_symmetry.py
src/magnetic_spacegroup.c
src/primitive.c
src/spacegroup.c
src/spacegroup.h
src/spglib.c
src/spglib.h
src/test.c

`spg_get_spacegroup_type_from_symmetry` is implemented to replace `spg_get_hall_number_from_symmetry` that is deprecated at v2.0.

Implement spg_get_spacegroup_type_from_symmetry

---

src/spin.c
src/symmetry.c

- (`symmetry.c`) Just to make it easy to read.
- (`spin.c`) Simplify passing arguments

Minor refactoring

---

CMakeLists.txt
fortran/CMakeLists.txt
fortran/spglib_f08.pc.cmake
spglib.pc.cmake

The pkgconfig file is architecture specific, so it needs
to be installed into libdir/pkgconfig. On Red Hat/SUSE
like distributions libdir is actually $prefix/lib64 on
64bit platforms.
Signed-off-by: Dirk Müller <dirk@dmllr.de>

Install spglib pkgconfig into LIBDIR

---

test/CMakeLists.txt

Fixes https://github.com/spglib/spglib/issues/182.
When spglib.h appears several times in directoies specified by -I, -iquote,
-isystem, or -idirafter, older spglib.h may be chosen (especially when
installing spglib and C compiler via conda). To fix the inconsistency,
use static library of `symspg.so` for testing. Then, src/spglib.h is
searched first since it locates the same directory as other src/*.c
files.
@atztogo I've reproduced the test failures when installing compilers and spglib via Conda. 
Can you check this PR and, if it works, merge it?

Fix include-path problem in testing

---

src/magnetic_spacegroup.c
src/spin.c
test/README.md
test/test_magnetic_symmetry.cpp

Fixes: https://github.com/spglib/spglib/issues/186
When magnetic moments `m` and `-m` are equal up to `mag_symprec`,
m - (-m) = 2m < mag_symprec should be satisfied. Thus, we need to judge
`m` as zero up to `0.5 * mag_symprec`.

Tighten magnetic tolerance for judging type-II MSG

---

CMakeLists.txt

The library has some multiple variable names and macro names, leading to One Definition Rule problems with unity builds.
This cmake update excludes all sources from unity builds, letting them be compiled "normally"

Exclude sources from unity builds

---

.github/ISSUE_TEMPLATE/bug_report.md
doc/magnetic_symmetry_flags.md
src/overlap.c
src/spin.c
test/test_magnetic_symmetry.cpp

Fixes: https://github.com/spglib/spglib/issues/194
Time-reversal parts are searched after determining linear and
translation parts of symmetry operations by `get_dataset`. It
is impossible in theory but we rarely fail to overlap atoms
possibly due to too high symprec. In that case, skip the
symmetry operation.
@atztogo In some edge cases with high `symprec`, a symmetry operation in `DataContainer->exact_structure->Symmetry` does not follow `symprec` (on the other hand, the not-refined operation follows `symprec`).
In the current implementation for MSG search, permutations of sites are computed from `DataContainer->exact_structure->symmetry`. Then, the segmentation fault in https://github.com/spglib/spglib/issues/194 was caused.
This PR just skips such a suspicious operation and does not …

Skip to determine time-reversal part for non-overlapped operations

---

src/spglib.c
src/spin.c
test/test_magnetic_symmetry.cpp

Because we cannot assume magnetic symmetry search is always successful, this commit fixes gracefully to return NULL for such a difficult situation with possibly too high symprec and mag_symprec.

Fix possible segmentation fault in `get_magnetic_dataset`
